### ISSUE TITLE
VST 3 state keys issue?

### ISSUE THREAD

**Issue by lucianoiam** [DISTRHO/DPF#370]
Noticed a weird behavior with the old state API where a state key gets its last character chopped (tested on Reaper/Mac):

```
void Plugin::initState(uint32_t index, String& stateKey, String& defaultStateValue)
{
    if (index == 0) {
        stateKey = "state_1234";
        defaultStateValue = "-1";
    }
}

void UI::stateChanged(const char* key, const char* value)
{
    d_stderr(key);
}

```

Output is state_123 instead of state_1234.

d_parameters.vst3 works as expected but it uses the new API

**Comment by falkTX** [comment]
sounds like a +1 missing somewhere.
I didnt fully check the state API on vst3 properly yet, but this is a good find, so thanks.

**Comment by lucianoiam** [comment]
I am not familiar with the VST3 spec but could it be that those `:length` attributes need to account for '\0' when setting a string?

Found that doing this fixes the issue:

```
        v3_cpp_obj(attrlist)->set_int(attrlist, "key:length", std::strlen(key) + 1);
...
        v3_cpp_obj(attrlist)->set_string(attrlist, "key", ScopedUTF16String(key));
```

**Comment by lucianoiam** [comment]
FYI, without +1 the receiving end gets the string and surprise, instead of the last character you get \0. So someone is explicitly setting it halfway

**Comment by falkTX** [comment]
Weirdly this seems to only happen on some hosts.
Their Application Message implementation must be different from the official (that at least JUCE uses). The +1 on the length property seems to not be the right place for it.

My guess is that, when fetching data as string, some implementations assume the size includes null byte, and some don't.
Another yay for VST3 :sweat_smile:

**Comment by falkTX** [comment]
@lucianoiam should be fixed in e512b25281af5887033dae4bfb1c10c40c18fde7
Didn't test it myself as Carla does not show the issue, but I did try it to ensure there are no regressions.
I assume this fixes it, confirmation would be very nice, thanks.

**Comment by lucianoiam** [comment]
It works! thanks.

Spotted another issue with VST3 state which is still not fixed by this patch, will open a new issue soon.
