### ISSUE TITLE
DGL/Pugl

### ISSUE THREAD

**Issue by jmeekr** [DISTRHO/DPF#505]
Using the latest submodules in the imgui-template 

https://github.com/DISTRHO/imgui-template-plugin

https://github.com/DISTRHO/DPF/tree/79e5339bef455583a4b5762addfd6578d4230f05
https://github.com/DISTRHO/pugl/tree/93c3d70fe15eba1ece029ca8b86eb0c953a40a6d

My plugins for `clap` and `vst` crash both in Bitwig and `carla-single` under X11 because of, I assume, reparenting the window.
The jack standalone seems to work. 

I went to an older repository I had and checked the hashes:

https://github.com/DISTRHO/DPF/tree/4e63344dad5f1c81d6cb8a1323e258b733bb1c04
https://github.com/DISTRHO/pugl/commit/e33b2f6b0cea6d6263990aa9abe6a69fdfba5973

Changing to those commits, recompiling dpf, and recompiling the imgui template project, seems to work.  I tried 
to chase down which commit breaks it but it's kind of difficult to bisect.

**Comment by falkTX** [comment]
the update to pugl was mostly made in a single commit, I can guess it is the culprit.
best would be to build in debug mode and run the host through a debugger.

I dont have the crash myself, so have not noticed this. under which desktop and distro does this happen?

**Comment by jmeekr** [comment]
https://github.com/DISTRHO/pugl/blob/main/src/x11_gl.c#L73

This seems to be the line (in pugl) that keeps breaking on the `DPF` develop branch.

Running `cmake . && make` then running 

`carla-single native clap bin/d_info.clap` 

Will give 

```
[dpf] createNextWindow 405 256 1.000000
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Resource id in failed request:  0x0
  Serial number of failed request:  39
  Current serial number in output stream:  40
[carla] Carla assertion failure: "engine == nullptr" in file ../backend/CarlaHostImpl.hpp, line 87
[carla] Carla assertion failure: "! lib.canDelete" in file ../utils/CarlaLibCounter.hpp, line 46
```

I tried comparing the attributes that pugl sends for the `glXFbchooseconf` but I don't think those have 
really changed.  I have a hunch that it's the order of creating window/window properties before this 
gets called (`bad window` `invalid window parameter`).  So I've been running gdb with a breakpoint 
on `puglRealize`

If I run Carla (the latest git version) and load the plugin(s) from there, it will load the UI for 
the plugins.

For Reaper if I run as a seperate process it will give the same error.  However if I run it as a native process 
the plugins will work and load.

```
[dpf] createNextWindow 405 256 1.000000
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Resource id in failed request:  0x0
  Serial number of failed request:  39
  Current serial number in output stream:  40
Jack: JackClient::kXRunCallback
[dpf] createNextWindow 405 256 1.000000


```

I've also tried to run in Gnome, and Gnome classic with the same experience.

The opengl defines seem to have updated at some point in dpf?

If you have recommendations I can try I would appreciate it.  I'm not experienced with any of this workflow.

The most recent dpf commit that works is`4900b15`  which is `pugl-upstream`  `d4d964`.

**Comment by falkTX** [comment]
does it happen with the example plugins or just your own?

**Comment by jmeekr** [comment]
>  On some setups the initial size created was 0x0 which can cause crashes

Still seems to be producing the same error with the latest commit.

Regarding commit: https://github.com/DISTRHO/DPF/commit/61b1daded001da2fc10a20968f2c0530e18116f5 

I did spend some time trying to force width and height around there.

**Comment by TheOnlyJoey** [comment]
Ok ignore the re-open issue I mentioned (unrelated), but can confirm that CLAP and VST3 both refuse to open on bitwig with current develop. Same plugin's do open in reaper for me. (both d_states example and my own plugins).
This is happening for me both with a set resolution and with 0x0.

**Comment by falkTX** [comment]
I was able to reproduce this bug and investigated, was a regression in pugl.
Fixed in bbdcbf14625497c391e883c74b8bbb2db16412dc

PR submitted to upstream pugl for the fix.

**Comment by TheOnlyJoey** [comment]
Seems to have fixed it for me! both CLAP and VST3 now work in Bitwig and Reaper under Linux! Thanks <3

**Comment by TheOnlyJoey** [comment]
<img width="941" height="456" alt="Image" src="https://github.com/user-attachments/assets/a430b676-ae67-405f-a5c1-66e616547236" />

d_states still crashes on CLAP though

**Comment by TheOnlyJoey** [comment]
Update: CLAP also crashes on macOS
